### PR TITLE
Except TypeError on 4xx status code

### PR DESCRIPTION
**Pull request by kovacsbalu**
Fix "TypeError: list indices must be integers, not str".

### CODE REVIEW

**Comment by clokep** [comment]
@kovacsbalu Hi! Thanks for the pull request. Can you describe under what situation you're getting this error? At first glance it looks like this [might be tested](https://github.com/percipient/stronglib/blob/d4251843143b8b32d8b7dc2cafd8e657680171c9/tests/test_common.py#L97-L114) in our code already, but isn't.

**Comment by kovacsbalu** [comment]
@clokep Hi! I'm just playing with the usage example and tried to add existing domain.

**Comment by clokep** [comment]
Thanks! I (or someone else) will take a look at this today or tomorrow. 👍

**Comment by kovacsbalu** [comment]
Great, thx! I will create another PR when needed.

**Comment by clokep** [comment]
I just confirmed that this is actually a bug in our API! When providing a duplicate domain we should be returning something like: `{"detail":"Could not add domain "strongarm.test" because it already exists."}`, while we're currently returning: `["Could not add domain "strongarm.test" because it already exists."]`!

I think this PR still makes sense to try to get whatever content we can out of the exception condition though. Thank you for the PR!

Thanks for adding tests! 👍

**Pull request merged**
